function [scenario, egoCar] = ADSTScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.4 and Automated Driving System Toolbox 1.2.
% Generated on: 17-Aug-2018 13:22:39

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 100);

% Add all road segments
roadCenters = [5 0 0;
    5000 0 0];
laneSpecification = lanespec(2, 'Width', 9.925);
road(scenario, roadCenters, 'Lanes', laneSpecification);

% Add the ego car
egoCar = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [21.12 -4.8875 0]);
waypoints = [21.12 -4.8875 0;
    5000 -4.8875 0];
speed = 10;
trajectory(egoCar, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [1100 4.8875 0]);
waypoints = [1100 4.8875 0;
    5 4.8875 0];
speed = 10;
trajectory(car1, waypoints, speed);

car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [282.4 -4.8875 0]);
waypoints = [282.4 -4.8875 0;
    2500 -4.8875 0];
speed = 10;
trajectory(car2, waypoints, speed);

car3 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [570.5 -4.8875 0]);
waypoints = [570.5 -4.8875 0;
    2500 -4.8875 0];
speed = 10;
trajectory(car3, waypoints, speed);
car4 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [830 4.8875 0]);
waypoints = [830 4.8875 0;
    5 4.8875 0];
speed = 5;
trajectory(car4, waypoints, speed);
car5 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [120 -4.8875 0]);
waypoints = [120 -4.8875 0;
    5000 -4.8875 0];
speed = 5;
trajectory(car5, waypoints, speed);